import test from 'node:test';
import assert from 'node:assert/strict';
import {validateGraph,diffGraphs} from '../src/contract.mjs';
import {example} from './helpers.mjs';
const invalid=(name,mutate,regex)=>test(name,async()=>{const g=await example();mutate(g);assert.throws(()=>validateGraph(g),regex);});
test('commerce example validates without an analyzer',async()=>assert.equal(validateGraph(await example()).schemaVersion,1));
invalid('reject unknown schema version',g=>g.schemaVersion=9,/schemaVersion/);
invalid('reject duplicate node IDs',g=>g.nodes.push(g.nodes[0]),/duplicate/);
invalid('reject dangling edges',g=>g.edges[0].target='missing',/Dangling/);
invalid('reject missing evidence',g=>g.nodes[0].evidenceIds=['missing'],/missing/);
invalid('observed nodes need concrete evidence',g=>g.nodes[0].evidenceIds=['sample.inference'],/concrete evidence/);
invalid('observed edges need concrete evidence',g=>g.edges[0].evidenceIds=['sample.inference'],/concrete evidence/);
invalid('source evidence needs a locator',g=>delete g.evidence[0].locator,/locator/);
invalid('reject unsafe asset paths',g=>g.nodes[0].preview='../secret.png',/preview/);
invalid('reject external preview URLs',g=>g.nodes[0].preview='https://other.invalid/s.png',/preview/);
invalid('reject parent cycles',g=>{g.nodes[0].parentId=g.nodes[1].id;g.nodes[1].parentId=g.nodes[0].id;},/cycle/);
invalid('reject positions of nodes not in a view',g=>g.views[0].positions.missing={x:0,y:0},/outside/);
invalid('reject NaN coordinates',g=>g.views[0].positions['web.home'].x=NaN,/position/i);
invalid('reject contradictory verified status',g=>g.reports[2].status='verified',/passed/);
invalid('measured performance requires measurement evidence',g=>g.reports[1].metrics[0].kind='measured',/measurement/);
invalid('executed test requires test evidence',g=>g.reports[2].tests[0].evidenceIds=['sample.source'],/test evidence/);
invalid('impact paths must end at affected target',g=>g.reports[0].affected[0].pathEdgeIds=['catalog.api'],/end/);
invalid('impact paths must be contiguous',g=>g.reports[0].affected[0].pathEdgeIds=['catalog.api','flow.cart-checkout'],/contiguous/);
invalid('reject prototype mutation keys',g=>g.nodes[0].metadata=JSON.parse('{"__proto__":{"pwned":true}}'),/Unsafe key/);
invalid('demo flag must be explicit',g=>delete g.project.demo,/demo/);
test('new frameworks can be represented without a registry',async()=>{const g=await example();g.nodes[0].metadata={framework:'AnUnseenStack',runtime:'custom'};assert.doesNotThrow(()=>validateGraph(g));});
test('zero means measured zero while null means unknown',async()=>{const g=await example();g.reports[1].metrics[0].before=0;g.reports[1].metrics[0].after=null;assert.doesNotThrow(()=>validateGraph(g));});
test('data diff reports only actual changed fields',async()=>{const a=await example(),b=structuredClone(a);b.revision=1;b.nodes[0].label='새 홈';const d=diffGraphs(a,b);assert.deepEqual(d.nodes.updated,['web.home']);assert.deepEqual(d.edges.updated,[]);});
