import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable,Writable} from 'node:stream';
import {fixture} from './helpers.mjs';
import {runMcp,callTool,tools} from '../src/mcp.mjs';
async function rpc(store,messages){let output='';const input=Readable.from(messages.map(x=>typeof x==='string'?x+'\n':JSON.stringify(x)+'\n'));const sink=new Writable({write(chunk,encoding,cb){output+=chunk.toString();cb();}});await runMcp(store,'mcp-session',{input,output:sink});return output.trim().split('\n').filter(Boolean).map(JSON.parse);}
test('MCP initializes, lists tools and returns current selection',async t=>{const {store}=await fixture(t);await store.select('mcp-session',{nodeIds:['web.products'],graphRevision:1});const r=await rpc(store,[{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18'}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/list'},{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'atlas_context',arguments:{}}}]);assert.equal(r.length,3);assert.equal(r[0].result.serverInfo.name,'codeatlas');assert.equal(r[1].result.tools.length,6);assert.deepEqual(JSON.parse(r[2].result.content[0].text).selection.nodeIds,['web.products']);});
test('MCP returns structured parse and unknown method errors',async t=>{const {store}=await fixture(t);const r=await rpc(store,['{bad',{jsonrpc:'2.0',id:1,method:'initialize',params:{}},{jsonrpc:'2.0',id:2,method:'runArbitraryShell'}]);assert.equal(r[0].error.code,-32700);assert.equal(r[2].error.code,-32601);});
test('MCP publish uses same revision and validation controls',async t=>{const {store}=await fixture(t);const g=await store.read();g.nodes[0].label='MCP updated';const r=await callTool(store,'mcp-session','atlas_publish',{graph:g,expectedRevision:1});assert.equal(r.revision,2);await assert.rejects(callTool(store,'mcp-session','atlas_publish',{graph:g,expectedRevision:1}),/conflict/);});
test('MCP tool errors do not terminate the connection',async t=>{const {store}=await fixture(t);const r=await rpc(store,[{jsonrpc:'2.0',id:1,method:'initialize',params:{}},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'unknown',arguments:{}}},{jsonrpc:'2.0',id:3,method:'ping'}]);assert.equal(r[1].result.isError,true);assert.deepEqual(r[2].result,{});});
test('MCP never advertises source execution or model tools',()=>{assert.deepEqual(tools().map(t=>t.name),['atlas_status','atlas_context','atlas_graph','atlas_publish','atlas_patch','atlas_validate']);});
